### ISSUE TITLE
No plugin exists with the handle "lever"

### ISSUE THREAD

**Issue by leemunroe** [workingconcept/lever-craft-plugin#1]
Hello, thanks for the plugin! I've successfully installed it locally and it made life a lot easier.

The problem is when I attempt to restart my local instance. I'm using Docker and when I try to bring it up I get the following message in my terminal logs:

```
CraftCMS    | Migrated up successfully.
CraftCMS    | Installing plugin "lever" ... error: No plugin exists with the handle "lever".
CraftCMS    | Aborting config sync
CraftCMS    | Yii Migration Tool (based on Yii v2.0.16)
CraftCMS    |
```

This just continues to loop and doesn't start. Any ideas what the issue could be here?

**Comment by mattstein** [comment]
Glad it’s useful, @leemunroe! I’ve been using the plugin with [DDEV](https://github.com/drud/ddev), a Docker-based local dev environment, without issue. I’m wondering whether you’ve got an issue with this plugin or something related to project config and your environment:

1. Do you have other plugins installed that aren’t being weird like this? (If not, can you pick any other plugin and repeat the same steps successfully?)
2. Can you reproduce the issue even if you’ve [disabled project config](https://docs.craftcms.com/v3/config/config-settings.html#useprojectconfigfile)?

If these are dead ends and this plugin’s still definitely relevant, I’ll need to learn more about your setup to try and reproduce the issue.

**Comment by leemunroe** [comment]
@mattstein Thanks for quick response. Yes turns out others have the same problem and this is likely something to do with my setup and local volume. Sorry to bother you and thanks for pointing me in the right direction.
