### ISSUE TITLE
Setting unknown property: workingconcept\lever\models\LeverJob::country

### ISSUE THREAD

**Issue by justinholtweb** [workingconcept/lever-craft-plugin#2]
Plugin started returning an error when calling the `LeverJob` class. `Setting unknown property: workingconcept\lever\models\LeverJob::country`. I assume possibly the API at Lever has changed?

Craft: Craft Pro 3.6.18
Lever: 1.0.3

**Comment by mattstein** [comment]
Looks like [they added `country` to the documentation](https://github.com/lever/postings-api/commit/af886379370b7478b44f1df17b1d61b14a80402f) on August 11th. I don’t have a Lever account to test with anymore and last I checked they didn’t offer developer-only accounts, but I can certainly YOLO-update the model here.

**Comment by justinholtweb** [comment]
@mattstein that would be awesome. I might be able to get you access to my client's Lever account if that would help?

**Comment by mattstein** [comment]
@justinholtweb I appreciate that, and I’d rather ask you to confirm success if you don’t mind. Assuming it’ll be painless and I can get to this soonish.

**Comment by justinholtweb** [comment]
@mattstein absolutely can, just let me know when you get a patch up and I can test right away. Thanks!

**Comment by mattstein** [comment]
Hey @justinholtweb, just added two new job properties in a [1.0.4](https://github.com/workingconcept/lever-craft-plugin/tree/1.0.4) branch. Would you mind giving that a try when you have a moment?

Their API docs say `country` data should start flowing in this month—explaining why you’re seeing it now—and `workplaceType` should start appearing in October. Both are accounted for here.

**Comment by justinholtweb** [comment]
@mattstein this worked!

**Comment by mattstein** [comment]
Lovely, I’ll tag a new release. Thanks for confirming @justinholtweb!

**Comment by mattstein** [comment]
This is in [1.0.4](https://github.com/workingconcept/lever-craft-plugin/releases/tag/1.0.4), which I just published. Thanks again!

**Comment by justinholtweb** [comment]
Thank you @mattstein
