### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by thegodshatetexas** [workingconcept/lever-craft-plugin#3]
My web host recently upgraded to PHP 8.1 and I am unable to update/install version 1.0.4. 

**Steps to reproduce:**

`composer install`

> Problem 1
    - workingconcept/craft-lever is locked to version 1.0.3 and an update of this package was not requested.
    - workingconcept/craft-lever 1.0.3 requires php ^7.0.0 -> your php version (8.1.10) does not satisfy that requirement.

**Potential Fix**

Update PHP requirement in `composer.json` with:
`"php": "^7.2.5|^8.1",`

**Comment by mattstein** [comment]
Thanks! Would you please try the `php8` branch here and confirm that works for you? I changed the requirement to `"php": "^7.0.0|^8.0.0"` since there’s no reason it has to be 8.1 or higher.

**Comment by thegodshatetexas** [comment]
@mattstein The `php8` branch fixed my issue! Thank you

**Comment by mattstein** [comment]
Great, thanks for confirming @thegodshatetexas! Just released version [1.0.5](https://github.com/workingconcept/lever-craft-plugin/releases/tag/1.0.5) with that change.
