### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by patrikalienus** [workingconcept/lever-craft-plugin#4]
Will there be (official) support for Craft 4?

I haven't tested it in Craft 4 personally yet, but as the plugins we use start to have support for v4, we will upgrade. It'd be nice if the Lever plugin kept up.

**Comment by mattstein** [comment]
Now that you ask, I suppose I should update it. It’s a pretty simple plugin so I’ll add Craft 4 support if people are using it.

**Comment by mattstein** [comment]
I started a branch [here](https://github.com/workingconcept/lever-craft-plugin/tree/craft4) but I need to get a sandbox account to test it.

**Comment by patrikalienus** [comment]
Awesome news. Obviously can't speak for everyone, but I'm enjoying it thus far :)

I guess more and more will use it as Lever grows.

**Comment by patrikalienus** [comment]
I am removing my vote for Craft 4 support. The company I'm working for have decided to not go with Lever after all. It's a neat, time-saving plugin for those that need it though.

**Comment by mattstein** [comment]
I’m still waiting to hear back about API testing access again, which didn’t go well a few years ago either. Will close this and publish the Craft 4 version if anyone else needs it or if I can test it independently. Thanks for following up!

**Comment by mattstein** [comment]
Got sandbox access and made a bunch of updates after testing! Just tagged version [2.0.0](https://github.com/workingconcept/lever-craft-plugin/releases/tag/2.0.0) with Craft 4 support. 🎉
